name: cscms-lottery-pick-winner

on:
  workflow_dispatch:
  schedule:
    - cron: '40 8 * * *'


jobs:
  pick-winner:
    runs-on: ubuntu-latest
    env:
      CSCMS_LOTTERY_ADDRESS: ${{ secrets.CSCMS_LOTTERY_ADDRESS }}
      CSCMS_LOTTERY_MNEMONIC: ${{ secrets.CSCMS_LOTTERY_MNEMONIC }}
      CSCMS_LOTTERY_PROVIDER_ENDPOINT: ${{ secrets.CSCMS_LOTTERY_PROVIDER_ENDPOINT }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: yarn
    - run: yarn cscms-lottery
